config/routes.rb
Rails.application.routes.draw do
  resources :algos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "algos#index"
end

app/models/algo.rb
class Algo < ApplicationRecord

# There should only be a ifxed number of type
# will have to alte the form to preload the types avail
# so users can choose. Below function will sort based on type
# which will be used to sort on the index page in each of the 
# cards. Then they should be able to expand the cards to 
# view all problems associated with said category of algorithms.

    def soted_by_type_of

    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/algos_controller.rb
class AlgosController < ApplicationController
  before_action :set_algo, only: %i[ show edit update destroy ]

  # GET /algos or /algos.json
  def index
    @algos = Algo.all
  end

  # GET /algos/1 or /algos/1.json
  def show
  end

  # GET /algos/new
  def new
    @algo = Algo.new
  end

  # GET /algos/1/edit
  def edit
  end

  # POST /algos or /algos.json
  def create
    @algo = Algo.new(algo_params)

    respond_to do |format|
      if @algo.save
        format.html { redirect_to algo_url(@algo), notice: "Algo was successfully created." }
        format.json { render :show, status: :created, location: @algo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @algo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /algos/1 or /algos/1.json
  def update
    respond_to do |format|
      if @algo.update(algo_params)
        format.html { redirect_to algo_url(@algo), notice: "Algo was successfully updated." }
        format.json { render :show, status: :ok, location: @algo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @algo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /algos/1 or /algos/1.json
  def destroy
    @algo.destroy

    respond_to do |format|
      format.html { redirect_to algos_url, notice: "Algo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_algo
      @algo = Algo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def algo_params
      params.require(:algo).permit(:display_name, :type_of, :completed, :difficulty, :solution, :link_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/algos_helper.rb
module AlgosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/algos/_algo.html.erb
<div id="<%= dom_id algo %>">
  <p>
    <strong>Display name:</strong>
    <%= algo.display_name %>
  </p>

  <p>
    <strong>Type of:</strong>
    <%= algo.type_of %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= algo.completed %>
  </p>

  <p>
    <strong>Difficulty:</strong>
    <%= algo.difficulty %>
  </p>

  <p>
    <strong>Solution:</strong>
    <%= algo.solution %>
  </p>

  <p>
    <strong>Link name:</strong>
    <%= algo.link_name %>
  </p>

  <p>
    <%= link_to "Show this algo", algo %>
  </p>

</div>

app/views/algos/_form.html.erb
<%= form_with(model: algo) do |form| %>
  <% if algo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(algo.errors.count, "error") %> prohibited this algo from being saved:</h2>

      <ul>
        <% algo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :display_name, style: "display: block" %>
    <%= form.text_field :display_name %>
  </div>

  <div>
    <%= form.label :type_of, style: "display: block" %>
    <%= form.text_field :type_of %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.label :difficulty, style: "display: block" %>
    <%= form.text_field :difficulty %>
  </div>

  <div>
    <%= form.label :solution, style: "display: block" %>
    <%= form.text_area :solution %>
  </div>

  <div>
    <%= form.label :link_name, style: "display: block" %>
    <%= form.text_area :link_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/algos/edit.html.erb
<h1>Editing algo</h1>

<%= render "form", algo: @algo %>

<br>

<div>
  <%= link_to "Show this algo", @algo %> |
  <%= link_to "Back to algos", algos_path %>
</div>

app/views/algos/index.html.erb
<%= javascript_import_module_tag "index" %>

<div id="algos">
  <% @algos.each do |algo| %>
    <div class="container is-widescreen">
        <div class="columns">
          <div class="column is-full">
            <div class="notification is-info">
              <section class="section">
                <div class="container">
                  <div class="card is-fullwidth">
                    <header class="card-header">
                      <p class="card-header-title"><%=algo.display_name%></p>
                    </header>
                    <div class="card-content is-hidden">
                      <div class="content">
                        <%= render algo%>
                      </div>
                    </div>
                  </div>
              </section>
            </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/algos/new.html.erb
<h1>New algo</h1>

<%= render "form", algo: @algo %>

<br>

<div>
  <%= link_to "Back to algos", algos_path %>
</div>

app/views/algos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @algo %>

<div>
  <%= link_to "Edit this algo", edit_algo_path(@algo) %> |
  <%= link_to "Back to algos", algos_path %>

  <%= button_to "Destroy this algo", @algo, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmateurAlgoHours</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
        <%# this is the way to incorporate ERB/HTML class with bulma %>
          <%= link_to "Home", root_path, class: "navbar-item" %>

          <a class="navbar-item">
            <%=link_to "Create", new_algo_path, class: "navbar-item"%>
          </a>
<%# 
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item">
                About
              </a>
              <a class="navbar-item">
                Jobs
              </a>
              <a class="navbar-item">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
        </div> %>

        <%# <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div> %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>